% b = textscan(fopen('age_groups.csv'), '%s %d %d', 'delimiter', ',')
%g1 = bar(b{2}); set(gca, 'XTickLabel', b{1}); set(gca, 'FontSize', 11); title('Number of LinkR Users binned by Age Group');

function plot_age_groups(yvector1)
%CREATEFIGURE(YVECTOR1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 19-Jan-2012 13:59:52

% Create figure
figure1 = figure('Renderer','painters','PaperType','<custom>',...
    'PaperSize',[17 11],...
    'InvertHardcopy','off',...
    'Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,...
    'XTickLabel',{'13-20','21-30','31-40','41-50','51-60','61-70','71-80','81-90','91-100'},...
    'XTick',[1 2 3 4 5 6 7 8 9]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 10]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 60]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
hold(axes1,'all');

% Create bar
bar(yvector1);

% Create title
title('Number of LinkR Users binned by Age Group');

